### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/virgil_the-aeneid_john-dryden#4]
"curd" should be "cur’d":

https://github.com/standardebooks/virgil_the-aeneid_john-dryden/blob/76465f353017b3cd0d2ce14f00531f05d13bd00d/src/epub/text/book-10.xhtml#L946

"odorous" should be "od’rous" (also, in the original, the strange word "panacee" is italicized):

https://github.com/standardebooks/virgil_the-aeneid_john-dryden/blob/76465f353017b3cd0d2ce14f00531f05d13bd00d/src/epub/text/book-12.xhtml#L1288

**Comment by acabal** [comment]
Thanks, these should be fixed now!
